name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Profile Readme Development Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@V3
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_PROJECTS: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
          SYMBOL_VERSION : 2
          SHOW_SHORT_INFO: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LANGUAGE: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_OS: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_EDITORS: "True"
          SHOW_TIMEZONE: "True"
          LOCALE: en
